kind: pipeline
type: docker
name: development

platform:
  os: linux
  arch: arm

trigger:
  branch:
    - master
  event:
    - pull_request

concurrency:
  limit: 1

clone:
  disable: true

steps:
  - name: clone
    image: 192.168.1.125:5000/cleep-git:latest
    network_mode: host
    privileged: true
    commands:
      - git clone $DRONE_REMOTE_URL cleep-dev
      - ls -la
      - cd cleep-dev
      - git checkout $DRONE_SOURCE_BRANCH

  - name: build
    image: 192.168.1.125:5000/cleep/cleep:0.0.29
    network_mode: host
    privileged: true
    environment:
      SENTRY_DSN:
        from_secret: sentry_dsn
    commands:
      - apt-get -o Acquire::ForceIPv4=true -qq update
      - apt-get -o Acquire::ForceIPv4=true -qq -y install python3 wget python3-distutils python3-dev devscripts python3-all python3-setuptools
      - python3 -m pip -q --no-color install cleepcli pip --upgrade
      - python3 -m pip freeze | grep cleepcli
      - export REPO_DIR=/drone/src/cleep-dev
      - cleep-cli corebuild
      - pwd
      - ls -la

  - name: build-cleep-docker-image
    image: 192.168.1.125:5000/cleep-utils:20230205
    network_mode: host
    privileged: true
    commands:
      - # MUST BE RAN AFTER test-install STEP
      - echo 0.0.30 > version.txt
      - test -f version.txt || echo "No version.txt file found. Cannot continue"
      - docker --version
      - export VERSION=`cat version.txt`
      - echo $VERSION
      - cp -a "cleep_$VERSION_armhf.deb" "cleep.deb"
      - ls -la
      - docker build -f Dockerfile -t 192.168.1.125:5000/cleep/cleep:$VERSION .
      - docker push 192.168.1.125:5000/cleep/cleep:$VERSION


---
kind: pipeline
type: docker
name: release-candidate

platform:
  os: linux
  arch: arm

trigger:
  branch:
    - master
  event:
    - tag
  ref:
    - refs/tags/v*-rc*

concurrency:
  limit: 1

clone:
  disable: true

steps:
  - name: clone
    image: 192.168.1.125:5000/cleep-git:latest
    network_mode: host
    privileged: true
    commands:
      - git clone $DRONE_REMOTE_URL cleep-dev
      - ls -la
      - cd cleep-dev
      - git checkout $DRONE_SOURCE_BRANCH

  - name: run-tests
    image: 192.168.1.125:5000/cleep/cleep:0.0.29
    network_mode: host
    privileged: true
    commands:
      - python3 -m pip -q --no-color install cleepcli pip --upgrade
      - python3 -m pip freeze | grep cleepcli
      - cd cleep-dev
      - python3 -m pip install -r requirements-test.txt
      - export REPO_DIR=/drone/src/cleep-dev
      - cleep-cli coresync
      - cleep-cli coretests --coverage --output

  - name: build
    image: 192.168.1.125:5000/cleep/cleep:0.0.29
    network_mode: host
    privileged: true
    environment:
      SENTRY_DSN:
        from_secret: sentry_dsn
    commands:
      - apt-get -o Acquire::ForceIPv4=true -qq update
      - apt-get -o Acquire::ForceIPv4=true -qq -y install python3 wget python3-distutils python3-dev devscripts python3-all python3-setuptools
      - python3 -m pip -q --no-color install cleepcli pip --upgrade
      - python3 -m pip freeze | grep cleepcli
      - export REPO_DIR=/drone/src/cleep-dev
      - cleep-cli corebuild
      - pwd
      - ls -la

  - name: test-install
    image: 192.168.1.125:5000/cleep/cleep:0.0.29
    network_mode: host
    privileged: true
    commands:
      - apt-get install --yes --fix-broken ./cleep_*_armhf.deb
      - cleep --noro --stdout --dryrun
      - cleep --version > version.txt

  - name: publish-docs
    image: 192.168.1.125:5000/cleep/cleep:0.0.29
    network_mode: host
    privileged: true
    environment:
      ID_ED25519:
        from_secret: id_ed25519
      ID_ED25519_PUB:
        from_secret: id_ed25519_pub
    commands:
      - python3 -m pip -q --no-color install cleepcli pip --upgrade
      - python3 -m pip freeze | grep cleepcli
      - # configure ssh
      - mkdir -p ~/.ssh
      - echo "$ID_ED25519" > ~/.ssh/id_ed25519
      - chmod 600 ~/.ssh/id_ed25519
      - echo "$ID_ED25519_PUB" > ~/.ssh/id_ed25519.pub
      - chmod 644 ~/.ssh/id_ed25519.pub
      - ssh-keyscan github.com >> githubKey
      - ssh-keygen -lf githubKey
      - cat githubKey > ~/.ssh/known_hosts
      - # configure git
      - cd cleep-dev
      - git config --global user.email "drone@localhost"
      - git config --global user.name "drone"
      - export REPO_DIR=/drone/src/cleep-dev
      - cleep-cli coredocs --publish

  - name: publish-debian-package
    image: 192.168.1.125:5000/cleep/cleep:0.0.29
    network_mode: host
    privileged: true
    environment:
      GITHUB_ACCESS_TOKEN:
        from_secret: github_access_token
    commands:
      - # MUST BE RAN AFTER test-install STEP
      - test -f version.txt || echo "No version.txt file found. Cannot continue"
      - python3 -m pip -q --no-color install cleepcli pip --upgrade
      - export VERSION=`cat version.txt`
      - echo $VERSION
      - export REPO_DIR=/drone/src/cleep-dev
      - cleep-cli corepublish --version=$VERSION


---
kind: pipeline
type: docker
name: release

platform:
  os: linux
  arch: arm

trigger:
  branch:
    - master
  event:
    - tag
  ref:
    exclude:
    - refs/tags/v*-rc*

concurrency:
  limit: 1

clone:
  disable: true

steps:
  - name: clone
    image: 192.168.1.125:5000/cleep-git:latest
    network_mode: host
    privileged: true
    commands:
      - git clone $DRONE_REMOTE_URL cleep-dev
      - ls -la
      - cd cleep-dev
      - git checkout $DRONE_SOURCE_BRANCH

  - name: build
    image: 192.168.1.125:5000/cleep/cleep:0.0.29
    network_mode: host
    privileged: true
    environment:
      SENTRY_DSN:
        from_secret: sentry_dsn
    commands:
      - apt-get -o Acquire::ForceIPv4=true -qq update
      - apt-get -o Acquire::ForceIPv4=true -qq -y install python3 wget python3-distutils python3-dev devscripts python3-all python3-setuptools
      - python3 -m pip -q --no-color install cleepcli pip --upgrade
      - python3 -m pip freeze | grep cleepcli
      - export REPO_DIR=/drone/src/cleep-dev
      - cleep-cli corebuild
      - pwd
      - ls -la

  - name: test-install
    image: 192.168.1.125:5000/cleep/cleep:0.0.29
    network_mode: host
    privileged: true
    commands:
      - apt-get install --yes --fix-broken ./cleep_*_armhf.deb
      - cleep --noro --stdout --dryrun
      - cleep --version > version.txt

  - name: publish-deb
    image: 192.168.1.125:5000/cleep/cleep:0.0.29
    network_mode: host
    privileged: true
    environment:
      GITHUB_ACCESS_TOKEN:
        from_secret: github_access_token
    commands:
      - python3 -m pip -q --no-color install cleepcli pip --upgrade
      - export VERSION=`cat version.txt`
      - echo $VERSION
      - cleep-cli corepublish --version=$VERSION 

