kind: pipeline
type: docker
name: check-branch

platform:
  arch: arm

trigger:
  branch:
    - master
  event:
    - pull_request

concurrency:
  limit: 1

clone:
  disable: true

steps:
  - name: clone
    image: 192.168.1.125:5000/cleep-git:latest
    network_mode: host
    privileged: true
    commands:
      - git clone $DRONE_REMOTE_URL cleep-dev
      - ls -la
      - cd cleep-dev
      - git checkout $DRONE_SOURCE_BRANCH

  - name: core-validation
    image: 192.168.1.125:5000/raspberrypios/buster:20211202
    network_mode: host
    privileged: true
    commands:
      - ls -la
      - apt-get -o Acquire::ForceIPv4=true update
      - apt-get -o Acquire::ForceIPv4=true -y install python3 wget python3-distutils python3-dev
      - wget -O get-pip.py https://bootstrap.pypa.io/get-pip.py 
      - python3 get-pip.py
      - python3 --version
      - python3 -m pip install cleepcli
      - pwd
      - REPO_DIR=/drone/src/cleep-dev cleep-cli coretests
