kind: pipeline
type: docker
name: check-branch

platform:
  arch: arm

trigger:
  branch:
    - master
  event:
    - pull_request

concurrency:
  limit: 1

clone:
  disable: true

steps:
  - name: clone
    image: 192.168.1.125:5000/cleep-git:latest
  - name: prepare-env
    image: 192.168.1.125:5000/raspberrypios/buster:20211202
    commands:
      - printenv
      - ls -la
      - apt-get -o Acquire::ForceIPv4=true update
      - python -m ensurepip --upgrade
      - python3 --version
      - python3 -m pip install cleepcli
  - name: tests
    image: 192.168.1.125:5000/raspberrypios/buster:20211202
    commands:
      - cleep-cli coretests
