kind: pipeline
type: docker
name: check

platform:
  os: linux
  arch: arm

trigger:
  branch:
    - master
  event:
    - pull_request

concurrency:
  limit: 1

clone:
  disable: true

steps:
  - name: clone
    image: 192.168.1.125:5000/cleep-git:latest
    network_mode: host
    privileged: true
    commands:
      - git clone $DRONE_REMOTE_URL cleep-dev
      - ls -la
      - cd cleep-dev
      - git checkout $DRONE_SOURCE_BRANCH

  - name: unit-tests
    image: 192.168.1.125:5000/cleep/cleep:0.0.29
    network_mode: host
    privileged: true
    commands:
      - python3 -m pip -q --no-color install cleepcli pip --upgrade
      - python3 -m pip freeze | grep cleepcli
      - cd cleep-dev
      - python3 -m pip install -r requirements-test.txt
      - export REPO_DIR=/drone/src/cleep-dev
      - cleep-cli coresync
      - cleep-cli coretests --coverage --output

  - name: build
    image: 192.168.1.125:5000/cleep/cleep:0.0.29
    network_mode: host
    privileged: true
    environment:
      SENTRY_DSN:
        from_secret: sentry_dsn
    commands:
      - apt-get -o Acquire::ForceIPv4=true update
      - apt-get -o Acquire::ForceIPv4=true -y install python3 wget python3-distutils python3-dev devscripts python3-all python3-setuptools
      - python3 -m pip -q --no-color install cleepcli pip --upgrade
      - python3 -m pip freeze | grep cleepcli
      - export REPO_DIR=/drone/src/cleep-dev
      - cleep-cli corebuild

---
kind: pipeline
type: docker
name: release

platform:
  os: linux
  arch: arm

trigger:
  branch:
    - master
  event:
    - tag

concurrency:
  limit: 1

clone:
  disable: true

steps:
  - name: clone
    image: 192.168.1.125:5000/cleep-git:latest
    network_mode: host
    privileged: true
    commands:
      - git clone $DRONE_REMOTE_URL cleep-dev
      - ls -la
      - cd cleep-dev
      - git checkout $DRONE_SOURCE_BRANCH

  - name: core
    image: 192.168.1.125:5000/raspberrypios/buster:20211202
    network_mode: host
    privileged: true
    environment:
      SENTRY_DSN:
        from_secret: sentry_dsn
    commands:
      - ls -la
      - echo "Preparing environment..."
      - apt-get -o Acquire::ForceIPv4=true update
      - apt-get -o Acquire::ForceIPv4=true -y install python3 wget python3-distutils python3-dev devscripts python3-all python3-setuptools
      - wget -O get-pip.py https://bootstrap.pypa.io/get-pip.py 
      - python3 get-pip.py
      - python3 --version
      - python3 -m pip install cleepcli
      - echo "Building Cleep..."
      - printenv
      - export REPO_DIR=/drone/src/cleep-dev
      - SENTRY_DSN=$SENTRY_DSN cleep-cli corebuild
      - echo "Installing Cleep..."
      - ls -la
      - apt-get install --yes --allow-unauthenticated --allow-downgrades --allow-remove-essential --allow-change-held-packages ./cleep_*_armhf.deb
      - echo "Executing tests..."
      - cleep-cli coretests

