#!/bin/sh
echo "Enabling raspiot at startup"
/etc/raspiot/enable_raspiot_service.sh
echo ""

#install python dependencies
echo "Installing python dependencies..."
pip install -r /etc/raspiot/.requirements.txt
echo "Done"
