#!/bin/sh

#https://wiki.debian.org/MaintainerScripts

set -e

case "$1" in
    remove)
        ;; 

    purge)
        ;; 

    upgrade)
        ;;

    abort-install)
        ;; 

    abort-upgrade | failed-upgrade)
        # restore backuped apps
        rm -rf /opt/cleep/modules
        cp -a /opt/cleep/modules.backup /opt/cleep/modules
        ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        ;;
esac

#DEBHELPER#

exit 0

