#!/bin/bash

# https://wiki.debian.org/MaintainerScripts

set -e

# Check command result
# $1: command result (usually $?)
# $2: awaited command result
checkResult() {
    if [ $1 -ne $2 ]
    then
        echo ""
        echo "Error occured. Please check command output."
        exit 1
    fi  
}

case "$1" in
    install | upgrade)
        # install pip (or upgrade if necessary)
        echo "Installing pip..."
        wget -q --no-check-certificate "https://bootstrap.pypa.io/get-pip.py" -O /tmp/get-pip.py
        checkResult $? 0
        python3 /tmp/get-pip.py --trusted-host pypi.python.org
        checkResult $? 0
        rm -f /tmp/get-pip.py
        echo "Done"
        echo ""

        # install python dependencies
        echo "Installing python dependencies..."
        python3 -m pip install --no-cache-dir --trusted-host pypi.python.org "gevent==21.1.2" "greenlet==1.0.0" "bottle==0.12.19" "pyre-gevent==0.2.3" "netifaces==0.10.9" "uptime==3.0.1" "urllib3==1.26.3" "psutil==5.8.0" "passlib==1.7.4" "simplejson==3.17.2" "sentry-sdk==1.0.0" "pytz==2021.1" "reverse-geocode==1.4.1" "timezonefinder==5.2.0" "tzlocal==2.1" "mock>=4.0.3" "python-dateutil==2.8.1"
        checkResult $? 0
        echo "Done"
        echo ""
        ;;

    *)
        echo "preinst called with unknown argument '$1'" >&2
        ;;
esac

#DEBHELPER#

exit 0

