#!/bin/sh

#https://wiki.debian.org/MaintainerScripts

set -e

case "$1" in
    remove)
        # disable Cleep from startup
        /etc/cleep/cleephelper.sh disable
        # stop Cleep
        /etc/cleep/cleephelper.sh stop
        ;; 

    upgrade)
        # after upgrade let cleep restart by itself
        ;;
        
    failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument '$1'" >&2
        ;;
esac

#DEBHELPER#

exit 0

