#!/bin/sh

#https://wiki.debian.org/MaintainerScripts

set -e

case "$1" in
    remove)
        # disable Cleep from startup
        /etc/cleep/cleephelper.sh disable
        # stop Cleep
        /etc/cleep/cleephelper.sh stop
        # clear apps
        rm -rf /opt/cleep
        rm -rf /var/opt/cleep
        ;; 

    upgrade)
        # backup mandatory apps
        rm -rf /opt/cleep/modules.backup
        cp -a /opt/cleep/modules /opt/cleep/modules.backup
        ;;
        
    failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument '$1'" >&2
        ;;
esac

#DEBHELPER#

exit 0

