#!/bin/sh
### BEGIN INIT INFO
# Provides: cleep
# Required-Start:   $syslog $local_fs 
# Required-Stop:    $syslog $local_fs 
# Default-Start:    2 3 4 5
# Default-Stop:     0 1 6
# Short-Description: Cleep application
### END INIT INFO

. /lib/lsb/init-functions
[ -f /etc/default/cleep.conf ] && . /etc/default/cleep.conf

BIN_PATH=/usr/bin/
PID_PATH=/var/run/
DAEMON_USER=root
DAEMON_GROUP=root
APP=cleep
DESC=Cleep

start_module() {
    start-stop-daemon --start --quiet --background --chuid $DAEMON_USER:$DAEMON_GROUP --pidfile "$3" --make-pidfile --exec "/usr/bin/env SENTRY_DSN=$SENTRY_DSN $2" -- "$4"
    if [ $? -ne 0 ]; then
        log_failure_msg "Failed"
        exit 1
    fi
    if [ $? -eq 0 ]; then
        log_success_msg "Done"
    fi
}

start() {
    echo "Starting $DESC..."
    if [ -f "$BIN_PATH$APP" ]
    then
        start_module "$APP" "$BIN_PATH$APP" "$PID_PATH$APP.pid"
    fi
}

stop_module() {
    start-stop-daemon --stop --quiet --oknodo --pidfile "$3"
    if [ $? -ne 0 ]; then
        log_failure_msg "Failed"
        exit 1
    fi
    if [ $? -eq 0 ]; then
        log_success_msg "Done"
    fi
}

stop() {
    echo "Stopping $DESC..."
    if [ -f "$BIN_PATH$APP" ]
    then
        stop_module "$APP" "$BIN_PATH$APP" "$PID_PATH$APP.pid"
    fi
}

force_reload() {
    stop
    start
}

status() {
    run=`pgrep -f /usr/bin/cleep | wc -l`
    if [ $run -eq 1 ]
    then
        echo "$APP is running"
    else
        echo "$APP is NOT running"
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    force-reload)
        force_reload
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $DESC {start|stop|force-reload|restart}"
        exit 2
esac
